// Generated by CoffeeScript 2.1.1
(function() {
  var path;

  path = require('path');

  module.exports = function() {
    var context, root;
    ({context, root} = this);
    // Function for `@use`:
    this.register('static', function(options) {
      var p, ref;
      if (typeof options === 'string') {
        options = {
          path: options
        };
      }
      if (options == null) {
        options = {};
      }
      p = (ref = options.path) != null ? ref : path.join(root, '/public');
      delete options.path;
      return context.express.static(p, options);
    });
  };

}).call(this);
